import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '../globals.css';
import StoreProvider from '../store-provider';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';

const inter = localFont({
  src: '../fonts/inter-variable.ttf',
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = await getMessages();
  return (
    <html lang={locale}>
      <body className={`${inter.variable} font-inter`}>
        <StoreProvider>
          <NextIntlClientProvider messages={messages}>{children}</NextIntlClientProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
